#ifndef SinShader_COMPUTE
#define SinShader_COMPUTE

float SinMat_sin;

// [shader(SinShader)]

void SinShader_SecRays(
    inout Ray ray,
    RayHit hit,
    inout SecRaysAtHit secRaysAtHit
) 
{
}

float3 SinShader(
   inout Ray ray,
   RayHit hit,
   float3 ambientLightUpper,
   float3 secondaryRayColor
)
{
   return float3(SinMat_sin, SinMat_sin, SinMat_sin);
}

float3 SinShader_OnShadowRayHit(Ray ray, RayHit hit)
{
    return float3(0, 0, 0); // Opaque
}


#endif // SinShader_COMPUTE 