#ifndef RAYHIT_COMPUTE
#define RAYHIT_COMPUTE

struct RayHit
{
    float3 barycentric;
    float distance;
    int primitiveId;  // the unique id for each primitive
    float3 position;
    float3 normal;
};

RayHit CreateRayHit()
{
    RayHit hit;
    hit.barycentric = float3(1.0f, 0.0f, 0.0f);
    hit.position = float3(0.0f, 0.0f, 0.0f);
    hit.distance = 1.#INF;
    hit.normal = float3(0.0f, 0.0f, 0.0f);
    hit.primitiveId = -1;
    return hit;
}

#endif  // RAYHIT_COMPUTE
